spring.application.name=jobportal

server.port=8585

##local database
#spring.datasource.url=jdbc:mysql://43.255.154.110:3306/bakers_db?useSSL=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=bakers_us
#spring.datasource.password=bakers_pw123

#local database
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

#server when running on local
#spring.datasource.url=jdbc:mysql://157.20.214.180:3306/app?useSSL=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=zplus#daily4you

#server when creating jar
#spring.datasource.url=jdbc:mysql://db:3306/app?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=zplus#daily4you

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true





