spring.application.name=jobportal

server.address=0.0.0.0
server.port=8090


spring.datasource.url=jdbc:mysql://147.93.31.4:3306/job_portal
spring.datasource.username=root
spring.datasource.password=elitecodo_pw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#server when running on local
#spring.datasource.url=jdbc:mysql://157.20.214.180:3306/app?useSSL=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=zplus#daily4you

#server when creating jar
#spring.datasource.url=jdbc:mysql://db:3306/app?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=zplus#daily4you

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# application.properties
python.scraper.url=https://python-scraper-84ov.onrender.com

##Sending otp on mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=sandeshmulay223@gmail.com

spring.mail.username=scoopenjobportal@gmail.com
spring.mail.password=fkdk omgj dkbo hzli

#spring.mail.password=sdxm hypr dgal aytn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


